version: '3'

services:
  backend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - GOPATH=/go/src
    ports:
      - 8080:80
    tty: true
    volumes:
      - ./frontend:/go/src/frontend
  
  